#!/usr/bin/env python3
"""Build the library's lookup table from skill frontmatter.

The table is the first thing a vendor reads and the one artefact that must never
be hand-maintained: it is a projection of every skill's `recall` block, and a
hand-written copy goes stale the first time an advert changes. This script writes
both faces of it, the machine-readable index and the vendor-facing page.

    python3 scripts/build_lookup_table.py <library-root>

Writes <root>/lookup-table.json and <root>/docs/LOOKUP-TABLE.md.
Pass --check to verify the files on disk match what would be generated, and exit
non-zero when they do not. That is what CI runs.
"""

import glob, json, os, re, sys, collections

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml --break-system-packages")

PROPOSED = {"declare-context-on-commit"}

CATEGORY_X = {"compliance": 1, "editorial": 2, "workflow": 3, "appearance": 4, "capability": 5}

TYPE_BLURB = {
    "cms": "a digital publishing system, the point at which a page goes live",
    "playout": "a transmission system that takes items to air",
    "rundown": "a running order, where items are ordered and held",
    "mam": "a media asset manager, holding the media and its record",
    "distribution": "a social or syndication publisher serving an outside destination",
    "graphics": "a graphics system rendering something on screen",
    "ingest": "the point media enters the house",
    "verification": "a tool that checks whether media is what it claims to be",
    "multimodal": "a tool that reads picture, sound and text together",
    "transcription": "a speech to text tool, live or file based",
    "discovery": "a search or archive surfacing tool",
    "archive": "a long term store",
    "markets_data": "a market or data feed",
    "planning": "a planning or assignment system",
    "compliance_hub": "a compliance desk tool that holds and clears",
}


def frontmatter(path):
    t = open(path).read()
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", t, re.S)
    if not m:
        raise SystemExit(f"{path}: no frontmatter")
    return yaml.safe_load(m.group(1))


def collect(root):
    out = []
    for f in sorted(glob.glob(os.path.join(root, "skills", "*.md"))):
        fm = frontmatter(f)
        r = fm.get("recall") or {}
        out.append({
            "skill_id": fm["skill_id"],
            "name": fm["name"],
            "skill_version": fm["skill_version"],
            "som_schema_version": fm["som_schema_version"],
            "category": fm.get("category"),
            "lifecycle": fm.get("lifecycle"),
            "x": CATEGORY_X.get(fm.get("category")),
            "y": 5 if fm.get("origin") == "reference" else None,
            "z": None,
            "target_system_type": r.get("target_system_type") or [],
            "target_capability": r.get("target_capability"),
            "recall_on": fm.get("recall_on") or r.get("recall_on") or [],
            "conditions": r.get("conditions") or [],
            "in_library": fm["name"] not in PROPOSED,
        })
    return out


def build_json(rows):
    return {
        "note": "Generated by scripts/build_lookup_table.py from skills/*.md frontmatter. Do not hand edit. "
                "One row per skill in the library. Under proposal A the publishing house registers one row "
                "per configured instance on top of this, in its own registration layer; this file is the "
                "library half and carries no house values.",
        "rows": [r for r in rows if r["in_library"]],
        "proposed": [r for r in rows if not r["in_library"]],
    }


def build_md(rows):
    lib = [r for r in rows if r["in_library"]]
    prop = [r for r in rows if not r["in_library"]]
    by_type = collections.defaultdict(list)
    for r in lib:
        for t in r["target_system_type"]:
            by_type[t].append(r["name"])

    L = []
    A = L.append
    A("# The lookup table\n")
    A("**Generated by `scripts/build_lookup_table.py` from `skills/*.md`. Do not hand edit.** "
      "Every row below is a projection of a skill's `recall` block, so the table cannot say "
      "something the skill files do not.\n")
    A("This is step 1 of the on-ramp. Find your tool type, read the skills in your row, "
      "and stop there. Everything else in the pack is detail behind those files.\n")
    A("---\n")
    A('## Which skills does my tool type carry?\n')
    A("Match on what your tool **is being** in the workflow, not on who wrote it. One product "
      "declaring two types gets two different rows, which is the point of the table.\n")
    A("| Your `system_type` | Which means | Skills returned |")
    A("|---|---|---|")
    for t in sorted(by_type):
        names = ", ".join(f"`{n}`" for n in sorted(by_type[t]))
        A(f"| `{t}` | {TYPE_BLURB.get(t,'')} | {names} |")
    A("")
    A("A type that is not in this column returns nothing. That is a real answer and not a "
      "failure: it means no reference skill has been written for that kind of tool yet. "
      "`docs/SYSTEM-TYPE-VOCABULARIES.md` sets out the one place where it bites, which is "
      "plant control.\n")
    A("---\n")
    A("## The rows themselves\n")
    A("| Skill | Category | X | Y | Z | Targets | Woken by |")
    A("|---|---|---|---|---|---|---|")
    for r in sorted(lib, key=lambda r: (r["x"], r["name"])):
        A(f"| `{r['name']}` | {r['category']} | {r['x']} | {r['y']} | unset | "
          f"{', '.join('`'+t+'`' for t in r['target_system_type'])} | "
          f"{', '.join('`'+e+'`' for e in r['recall_on'])} |")
    A("")
    A("**X** comes from the category, **Y** from the origin, and **Z** is the publishing "
      "house's to assign. Every skill here is `origin: reference`, so Y is 5 for all of them, "
      "and Z is unset in the library because precedence between two skills a house has loaded "
      "is a house decision. A library that shipped Z would be ranking a customer's editorial "
      "priorities for them.\n")
    A("Everything here is `lifecycle: draft`. Nothing is ratified and no eval set has been run "
      "against a live implementation.\n")
    if prop:
        A("---\n")
        A("## Proposed, and in no package\n")
        for r in prop:
            A(f"- `{r['name']}` targets {', '.join('`'+t+'`' for t in r['target_system_type'])}. "
              f"It is a candidate and ships in no package. Its row is written in "
              f"`lookup-table-row.json` so a house can see the shape without the table indexing it.")
        A("")
    A("---\n")
    A("## What the table does not do\n")
    A("A match means a skill is **worth reading**, not that its condition holds. Recall is not "
      "evaluation: the executor still reads the story in front of it and decides. A table hit "
      "with a condition that does not hold produces nothing at all, quietly, and that is the "
      "normal case rather than an error.\n")
    A("The table indexes the library's generic skills. It does not carry any house's configured "
      "values. Under proposal A the house registers one advert row per configured instance in "
      "its own registration layer, which is what makes a configured instance findable; the "
      "library half, this file, stays the same for everybody.\n")
    return "\n".join(L) + "\n"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    root = args[0] if args else "."
    rows = collect(root)
    j = json.dumps(build_json(rows), indent=1) + "\n"
    m = build_md(rows)
    jp = os.path.join(root, "lookup-table.json")
    mp = os.path.join(root, "docs", "LOOKUP-TABLE.md")
    if check:
        bad = []
        for p, want in ((jp, j), (mp, m)):
            if not os.path.exists(p) or open(p).read() != want:
                bad.append(p)
        for p in bad:
            print(f"  ERROR    {os.path.relpath(p, root)} is not what the skill files generate. "
                  f"Run build_lookup_table.py.")
        print(f"\n  {'FAIL' if bad else 'PASS'} ({len(bad)} stale generated files)\n")
        sys.exit(1 if bad else 0)
    open(jp, "w").write(j)
    open(mp, "w").write(m)
    print(f"  wrote lookup-table.json ({len(rows)} skills) and docs/LOOKUP-TABLE.md")


if __name__ == "__main__":
    main()
